---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.demo-git.credentials.uri}
          # ONLY include username and pwd if the repo is private
          username: ${vcap.services.demo-git.credentials.username}
          password: ${vcap.services.demo-git.credentials.password}
  
security:
  user:
    name: {username}
    password: {password}
          
---

info:
  description: Training configuration repo